### ISSUE TITLE
Last version of the tutorial want a typesafe subscription

### ISSUE THREAD

**Issue by volothamp** [typesafehub/ReactiveMaps#25]
This app wants a typesafe.properties file in the project directory with a subscription key.

Am I missing something or this should be a free tutorial, without any subscription?

Here's the stack trace. 

java.lang.RuntimeException: == Typesafe Reactive Platform: typesafe.subscription key was not found in /Users/luca/Programmazione/scala/reactive-maps/project/typesafe.properties.
== Visit http://typesafe.com/account/id to obtain a trial subscription id.
	at scala.sys.package$.error(package.scala:27)

Many thanks

**Comment by havocp** [comment]
The current version demos Reactive Platform, so the two ways to get going are to get a free trial subscription ID (which has no time limit but isn't good for production use), or to remove project/project/typesafe.sbt in order to switch back to upstream Play.

Activator will have a nicer UI for this soon so you don't have to dig the error out of the logs.

**Comment by volothamp** [comment]
Thank you, that helped

**Comment by ktoso** [comment]
Glad to hear that, closing the ticket for now then :)
